import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MedBay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MedBay!</h1>

        <p className={styles.description}>
          Medical knowledge&#39;s home base
        </p>

        <div className={styles.grid}>
          <Link href="/thebay">
            <a className={styles.card}>
              <h2>The Bay &rarr;</h2>
              <p>Get your medical questions answered!</p>
            </a>
          </Link>
        </div>
      </main>

    </div>
  );
}
